const mainHira =[
    {id:'hira1',japan:'や',vietnam:'ya'},
    {id:'hira2',japan:'て',vietnam:'te'},
    {id:'hira3',japan:'あ',vietnam:'a'},
    {id:'hira4',japan:'み',vietnam:'mi'},
    {id:'hira5',japan:'う',vietnam:'u'},
    {id:'hira6',japan:'わ',vietnam:'wa'},
    {id:'hira7',japan:'ま',vietnam:'ma'},
    {id:'hira8',japan:'り',vietnam:'ri'},
    {id:'hira9',japan:'む',vietnam:'mu'},
    {id:'hira10',japan:'も',vietnam:'mo'},
    {id:'hira11',japan:'め',vietnam:'me'},
    {id:'hira12',japan:'れ',vietnam:'re'},
    {id:'hira13',japan:'と',vietnam:'to'},
    {id:'hira14',japan:'そ',vietnam:'so'},
    {id:'hira15',japan:'さ',vietnam:'sa'},
    {id:'hira16',japan:'ろ',vietnam:'ro'},
    {id:'hira17',japan:'つ',vietnam:'tsu'},
    {id:'hira18',japan:'お',vietnam:'o'},
    {id:'hira19',japan:'ち',vietnam:'chi'},
    {id:'hira20',japan:'ひ',vietnam:'hi'},
    {id:'hira21',japan:'ゆ',vietnam:'yu'},
    {id:'hira22',japan:'け',vietnam:'ke'},
    {id:'hira23',japan:'な',vietnam:'na'},
    {id:'hira24',japan:'か',vietnam:'ka'},
    {id:'hira25',japan:'ほ',vietnam:'ho'},
    {id:'hira26',japan:'ふ',vietnam:'fu'},
    {id:'hira27',japan:'く',vietnam:'ku'},
    {id:'hira28',japan:'い',vietnam:'i'},
    {id:'hira29',japan:'せ',vietnam:'se'},
    {id:'hira30',japan:'の',vietnam:'no'},
    {id:'hira31',japan:'ら',vietnam:'ra'},
    {id:'hira32',japan:'よ',vietnam:'yo'},
    {id:'hira33',japan:'へ',vietnam:'he'},
    {id:'hira34',japan:'ね',vietnam:'ne'},
    {id:'hira35',japan:'き',vietnam:'ki'},
    {id:'hira36',japan:'る',vietnam:'ru'},
    {id:'hira37',japan:'す',vietnam:'su'},
    {id:'hira38',japan:'し',vietnam:'shi'},
    {id:'hira39',japan:'は',vietnam:'ha'},
    {id:'hira40',japan:'を',vietnam:'wo'},
    {id:'hira41',japan:'え',vietnam:'e'},
    {id:'hira42',japan:'ぬ',vietnam:'nu'},
    {id:'hira43',japan:'に',vietnam:'ni'},
    {id:'hira44',japan:'こ',vietnam:'ko'},
    {id:'hira45',japan:'ん',vietnam:'n'},
    {id:'hira46',japan:'た',vietnam:'ta'},
]
const dakutenHira = [
    {id:'hira47',japan:'ぺ',vietnam:'pe'},
    {id:'hira48',japan:'ぱ',vietnam:'pa'},
    {id:'hira49',japan:'ぜ',vietnam:'ze'},
    {id:'hira50',japan:'げ',vietnam:'ge'},
    {id:'hira51',japan:'ぞ',vietnam:'zo'},
    {id:'hira52',japan:'ぼ',vietnam:'bo'},
    {id:'hira53',japan:'ぽ',vietnam:'po'},
    {id:'hira54',japan:'べ',vietnam:'be'},
    {id:'hira55',japan:'で',vietnam:'de'},
    {id:'hira56',japan:'づ',vietnam:'du'},
    {id:'hira57',japan:'び',vietnam:'bi'},
    {id:'hira58',japan:'ば',vietnam:'ba'},
    {id:'hira59',japan:'ぴ',vietnam:'pi'},
    {id:'hira60',japan:'ず',vietnam:'zu'},
    {id:'hira61',japan:'ど',vietnam:'do'},
    {id:'hira62',japan:'ぎ',vietnam:'gi'},
    {id:'hira63',japan:'が',vietnam:'ga'},
    {id:'hira64',japan:'ぶ',vietnam:'bu'},
    {id:'hira65',japan:'ぐ',vietnam:'gu'},
    {id:'hira66',japan:'ざ',vietnam:'za'},
    {id:'hira67',japan:'ご',vietnam:'go'},
    {id:'hira68',japan:'じ',vietnam:'zi'},
    {id:'hira69',japan:'だ',vietnam:'da'},
    {id:'hira70',japan:'ぷ',vietnam:'pu'},
    {id:'hira71',japan:'ぢ',vietnam:'da'},
]
const combineHira = [
    {id:'hira71',japan:'じゅ',vietnam:'zyu'},
    {id:'hira72',japan:'ぢょ',vietnam:'dyo'},
    {id:'hira73',japan:'りょ',vietnam:'ryo'},
    {id:'hira74',japan:'みゅ',vietnam:'myu'},
    {id:'hira75',japan:'にゅ',vietnam:'nyu'},
    {id:'hira76',japan:'ひゃ',vietnam:'hya'},
    {id:'hira77',japan:'しゅ',vietnam:'shyu'},
    {id:'hira78',japan:'びゃ',vietnam:'bya'},
    {id:'hira79',japan:'じょ',vietnam:'shyo'},
    {id:'hira80',japan:'ぴょ',vietnam:'pyo'},
    {id:'hira81',japan:'ぴゃ',vietnam:'pya'},
    {id:'hira82',japan:'きゃ',vietnam:'kya'},
    {id:'hira83',japan:'びょ',vietnam:'byo'},
    {id:'hira84',japan:'ぢゅ',vietnam:'dyu'},
    {id:'hira85',japan:'ひゅ',vietnam:'hyu'},
    {id:'hira86',japan:'みょ',vietnam:'myo'},
    {id:'hira87',japan:'きょ',vietnam:'kyo'},
    {id:'hira88',japan:'ちゅ',vietnam:'chyu'},
    {id:'hira89',japan:'りゅ',vietnam:'ryu'},
    {id:'hira90',japan:'ぎゅ',vietnam:'gyu'},
    {id:'hira91',japan:'ひょ',vietnam:'hyo'},
    {id:'hira92',japan:'びゅ',vietnam:'byu'},
    {id:'hira93',japan:'ぎゃ',vietnam:'gya'},
    {id:'hira94',japan:'ちゃ',vietnam:'chya'},
    {id:'hira95',japan:'にゃ',vietnam:'nya'},
    {id:'hira96',japan:'みゃ',vietnam:'mya'},
    {id:'hira97',japan:'ぎょ',vietnam:'gyo'},
    {id:'hira98',japan:'しゃ',vietnam:'shya'},
    {id:'hira99',japan:'ぴゅ',vietnam:'pyu'},
    {id:'hira100',japan:'しょ',vietnam:'shyo'},
    {id:'hira101',japan:'にょ',vietnam:'nyo'},
    {id:'hira102',japan:'じゃ',vietnam:'zya'},
    {id:'hira103',japan:'りゃ',vietnam:'rya'},
    {id:'hira104',japan:'きゅ',vietnam:'kyu'},
    {id:'hira105',japan:'ぢゃ',vietnam:'dya'},
    {id:'hira106',japan:'ちょ',vietnam:'chyo'},
]
const fullHira = mainHira.concat(dakutenHira).concat(combineHira);

const mainKana = [
    {id:'kata1',japan:'ヌ',vietnam:'nu'},
    {id:'kata2',japan:'ヤ',vietnam:'ya'},
    {id:'kata3',japan:'シ',vietnam:'si'},
    {id:'kata4',japan:'ユ',vietnam:'yu'},
    {id:'kata5',japan:'ノ',vietnam:'no'},
    {id:'kata6',japan:'ケ',vietnam:'ke'},
    {id:'kata7',japan:'ツ',vietnam:'tsu'},
    {id:'kata8',japan:'ワ',vietnam:'wa'},
    {id:'kata9',japan:'ヘ',vietnam:'he'},
    {id:'kata10',japan:'ナ',vietnam:'na'},
    {id:'kata11',japan:'タ',vietnam:'ta'},
    {id:'kata12',japan:'マ',vietnam:'ma'},
    {id:'kata13',japan:'レ',vietnam:'re'},
    {id:'kata14',japan:'サ',vietnam:'sa'},
    {id:'kata15',japan:'ヲ',vietnam:'wo'},
    {id:'kata16',japan:'ヒ',vietnam:'hi'},
    {id:'kata17',japan:'ン',vietnam:'n'},
    {id:'kata18',japan:'ラ',vietnam:'ra'},
    {id:'kata19',japan:'チ',vietnam:'chi'},
    {id:'kata20',japan:'テ',vietnam:'te'},
    {id:'kata21',japan:'メ',vietnam:'me'},
    {id:'kata22',japan:'ミ',vietnam:'mi'},
    {id:'kata23',japan:'ハ',vietnam:'ha'},
    {id:'kata24',japan:'モ',vietnam:'mo'},
    {id:'kata25',japan:'ソ',vietnam:'so'},
    {id:'kata26',japan:'コ',vietnam:'ko'},
    {id:'kata27',japan:'ホ',vietnam:'ho'},
    {id:'kata28',japan:'ス',vietnam:'su'},
    {id:'kata29',japan:'ア',vietnam:'a'},
    {id:'kata30',japan:'ム',vietnam:'mu'},
    {id:'kata31',japan:'ロ',vietnam:'ro'},
    {id:'kata32',japan:'カ',vietnam:'ka'},
    {id:'kata33',japan:'フ',vietnam:'fu'},
    {id:'kata34',japan:'セ',vietnam:'se'},
    {id:'kata35',japan:'キ',vietnam:'ki'},
    {id:'kata36',japan:'ク',vietnam:'ku'},
    {id:'kata37',japan:'ネ',vietnam:'ne'},
    {id:'kata38',japan:'エ',vietnam:'e'},
    {id:'kata39',japan:'オ',vietnam:'o'},
    {id:'kata40',japan:'イ',vietnam:'i'},
    {id:'kata41',japan:'ヨ',vietnam:'yo'},
    {id:'kata42',japan:'ニ',vietnam:'ni'},
    {id:'kata43',japan:'リ',vietnam:'ri'},
    {id:'kata44',japan:'ウ',vietnam:'u'},
    {id:'kata45',japan:'ル',vietnam:'ru'},
    {id:'kata46',japan:'ト',vietnam:'to'},
]
const dakutenKana = [
    {id:'kata46',japan:'デ',vietnam:'de'},
    {id:'kata47',japan:'ボ',vietnam:'bo'},
    {id:'kata48',japan:'ゴ',vietnam:'go'},
    {id:'kata49',japan:'ゾ',vietnam:'zo'},
    {id:'kata50',japan:'ダ',vietnam:'da'},
    {id:'kata51',japan:'ポ',vietnam:'po'},
    {id:'kata52',japan:'ヅ',vietnam:'zu'},
    {id:'kata53',japan:'パ',vietnam:'pa'},
    {id:'kata54',japan:'ペ',vietnam:'pe'},
    {id:'kata55',japan:'ド',vietnam:'do'},
    {id:'kata56',japan:'ヂ',vietnam:'di'},
    {id:'kata57',japan:'ジ',vietnam:'ji'},
    {id:'kata58',japan:'ブ',vietnam:'bu'},
    {id:'kata59',japan:'ギ',vietnam:'gi'},
    {id:'kata60',japan:'グ',vietnam:'gu'},
    {id:'kata61',japan:'ベ',vietnam:'be'},
    {id:'kata62',japan:'ザ',vietnam:'za'},
    {id:'kata63',japan:'ピ',vietnam:'pi'},
    {id:'kata64',japan:'ゼ',vietnam:'ze'},
    {id:'kata65',japan:'プ',vietnam:'pu'},
    {id:'kata66',japan:'ゲ',vietnam:'ge'},
    {id:'kata67',japan:'ビ',vietnam:'bi'},
    {id:'kata68',japan:'ガ',vietnam:'ga'},
    {id:'kata69',japan:'バ',vietnam:'ba'},
    {id:'kata70',japan:'ズ',vietnam:'zu'},
]
const combineKana =[
    {id:'kata71',japan:'ヂョ',vietnam:'dyo'},
    {id:'kata72',japan:'ヒャ',vietnam:'hya'},
    {id:'kata73',japan:'ピョ',vietnam:'pyo'},
    {id:'kata74',japan:'リュ',vietnam:'ryu'},
    {id:'kata75',japan:'ジャ',vietnam:'ja'},
    {id:'kata76',japan:'リャ',vietnam:'rya'},
    {id:'kata77',japan:'ビョ',vietnam:'byo'},
    {id:'kata78',japan:'キョ',vietnam:'kyo'},
    {id:'kata79',japan:'ニャ',vietnam:'nya'},
    {id:'kata80',japan:'ニョ',vietnam:'nyo'},
    {id:'kata81',japan:'ビャ',vietnam:'bya'},
    {id:'kata82',japan:'チョ',vietnam:'chyo'},
    {id:'kata83',japan:'ミャ',vietnam:'mya'},
    {id:'kata84',japan:'ギュ',vietnam:'gyu'},
    {id:'kata85',japan:'ヂャ',vietnam:'chya'},
    {id:'kata86',japan:'ジョ',vietnam:'jo'},
    {id:'kata87',japan:'ビュ',vietnam:'byu'},
    {id:'kata88',japan:'ピュ',vietnam:'pyu'},
    {id:'kata89',japan:'ヂュ',vietnam:'dyu'},
    {id:'kata90',japan:'チャ',vietnam:'dya'},
    {id:'kata91',japan:'ヒョ',vietnam:'hyo'},
    {id:'kata92',japan:'ピャ',vietnam:'pya'},
    {id:'kata93',japan:'リョ',vietnam:'ryo'},
    {id:'kata94',japan:'ミュ',vietnam:'myu'},
    {id:'kata95',japan:'ギャ',vietnam:'gya'},
    {id:'kata96',japan:'ミョ',vietnam:'myo'},
    {id:'kata97',japan:'キャ',vietnam:'kya'},
    {id:'kata98',japan:'シャ',vietnam:'shya'},
    {id:'kata99',japan:'ショ',vietnam:'shyo'},
    {id:'kata100',japan:'チュ',vietnam:'chyu'},
    {id:'kata101',japan:'キュ',vietnam:'kyu'},
    {id:'kata102',japan:'ニュ',vietnam:'nyu'},
    {id:'kata103',japan:'ヒュ',vietnam:'hyu'},
    {id:'kata104',japan:'シュ',vietnam:'shyu'},
    {id:'kata105',japan:'ギョ',vietnam:'gyo'},
    {id:'kata106',japan:'ジュ',vietnam:'ju'},
]
const fullKana = mainHira.concat(dakutenKana).concat(combineKana);
function renderKata(list,id){
    const el = document.getElementById(`${id}`);
    let content ='';
    list.forEach(item => {
        let temp = `
            <div class="quiz-item bd"  id = "${item.id}">
                    <div class="quiz-ques" >
                        <h1>${item.japan}</h1>  
                    </div>
                    <input type="text" id ="${item.vietnam}" onchange ="valid('${item.id}','${item.vietnam}','${item.vietnam}')">
                </div>
            `;
        content += temp;
    });
    el.innerHTML=content
}


function valid(frID,id,value){
    const z = document.getElementById(`${id}`);
    const x = document.getElementById(`${id}`).value;
    const y = document.getElementById(`${frID}`);
    
    if(x == `${value}`){
        console.log('true');
        y.style.border = '5px solid #00ff00';
        z.setAttribute("disabled", "");
    }else{
        console.log('false');
        z.value = '';
        y.style.border = '5px solid #f44336';

    }
}
